/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summarization/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize a hosts dataset
         * @description Summarize a Censys hosts dataset.
         */
        post: operations["summarize_hosts_summarization_hosts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summarization/web-properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize a web properties dataset
         * @description Summarize a Censys web properties dataset.
         */
        post: operations["summarize_web_properties_summarization_web_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summarization/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize a certificates dataset
         * @description Summarize a Censys certificates dataset.
         */
        post: operations["summarize_certificates_summarization_certificates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summarization/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize multiple datasets
         * @description Summarize multiple Censys datasets together.
         */
        post: operations["summarize_summarization_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutonomousSystem */
        AutonomousSystem: {
            /** Asn */
            asn: number;
            /** Name */
            name: string;
            /** Country Code */
            country_code?: string | null;
            /** Description */
            description?: string | null;
            /** Bgp Prefix */
            bgp_prefix?: string | null;
        };
        /** Body_summarize_summarization_summarize_post */
        Body_summarize_summarization_summarize_post: {
            hosts?: components["schemas"]["HostsDataset"] | null;
            web_properties?: components["schemas"]["WebPropertiesDataset"] | null;
            certificates?: components["schemas"]["CertificatesDataset"] | null;
        };
        /** Certificate */
        Certificate: {
            /** Fingerprint Sha256 */
            fingerprint_sha256: string;
            /** Fingerprint Sha1 */
            fingerprint_sha1?: string | null;
            /** Fingerprint Md5 */
            fingerprint_md5?: string | null;
            /** Domains */
            domains?: string[] | null;
            subject?: components["schemas"]["CertificateSubject"] | null;
            issuer?: components["schemas"]["CertificateIssuer"] | null;
            validity_period?: components["schemas"]["ValidityPeriod"] | null;
            key_info?: components["schemas"]["KeyInfo"] | null;
            certificate_authority?: components["schemas"]["CertificateAuthority"] | null;
            certificate_transparency?: components["schemas"]["CertificateTransparency"] | null;
            validation?: components["schemas"]["Validation"] | null;
            security_analysis?: components["schemas"]["SecurityAnalysis"] | null;
            usage_indicators?: components["schemas"]["UsageIndicators"] | null;
        };
        /** CertificateAuthority */
        CertificateAuthority: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Validation Level */
            validation_level?: string | null;
        };
        /** CertificateIssuer */
        CertificateIssuer: {
            /** Common Name */
            common_name?: string | null;
            /** Organization */
            organization?: string | null;
            /** Country */
            country?: string | null;
        };
        /** CertificateSubject */
        CertificateSubject: {
            /** Common Name */
            common_name?: string | null;
            /** Organization */
            organization?: string | null;
            /** Country */
            country?: string | null;
        };
        /** CertificateTransparency */
        CertificateTransparency: {
            /** Logs Count */
            logs_count?: number | null;
            /** First Seen */
            first_seen?: string | null;
            /** Logs */
            logs?: string[] | null;
        };
        /** CertificatesDataset */
        CertificatesDataset: {
            metadata: components["schemas"]["CertificatesDatasetMetadata"];
            /** Certificates */
            certificates: components["schemas"]["Certificate"][];
        };
        /** CertificatesDatasetMetadata */
        CertificatesDatasetMetadata: {
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Data Sources */
            data_sources?: string[] | null;
            /** Certificates Count */
            certificates_count?: number | null;
            /** Certificate Fingerprints */
            certificate_fingerprints?: string[] | null;
        };
        /** Coordinates */
        Coordinates: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** DNS */
        DNS: {
            /** Hostname */
            hostname?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Host */
        Host: {
            /** Ip */
            ip: string;
            location?: components["schemas"]["Location"] | null;
            autonomous_system?: components["schemas"]["AutonomousSystem"] | null;
            whois?: components["schemas"]["Whois"] | null;
            dns?: components["schemas"]["DNS"] | null;
            /** Services */
            services?: components["schemas"]["Service"][] | null;
            threat_intelligence?: components["schemas"]["ThreatIntelligence"] | null;
        };
        /** HostsDataset */
        HostsDataset: {
            metadata: components["schemas"]["HostsDatasetMetadata"];
            /** Hosts */
            hosts: components["schemas"]["Host"][];
        };
        /** HostsDatasetMetadata */
        HostsDatasetMetadata: {
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Data Sources */
            data_sources?: string[] | null;
            /** Hosts Count */
            hosts_count?: number | null;
            /** Ips Analyzed */
            ips_analyzed?: string[] | null;
        };
        /** KeyInfo */
        KeyInfo: {
            /** Algorithm */
            algorithm?: string | null;
            /** Key Size */
            key_size?: number | null;
            /** Public Key Fingerprint */
            public_key_fingerprint?: string | null;
        };
        /** Location */
        Location: {
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Province */
            province?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Continent */
            continent?: string | null;
        };
        /** SecurityAnalysis */
        SecurityAnalysis: {
            /** Zlint Status */
            zlint_status?: string | null;
            /** Failed Lints */
            failed_lints?: string[] | null;
            /** Risk Level */
            risk_level?: string | null;
        };
        /** Service */
        Service: {
            /** Port */
            port: number;
            /** Protocol */
            protocol: string;
            /** Banner */
            banner?: string | null;
            /** Banner Hash Sha256 */
            banner_hash_sha256?: string | null;
            /** Banner Hex */
            banner_hex?: string | null;
            /** Transport Protocol */
            transport_protocol?: string | null;
            /** Software */
            software?: components["schemas"]["Software"][] | null;
            /** Vulnerabilities */
            vulnerabilities?: components["schemas"]["Vulnerability"][] | null;
            /** Labels */
            labels?: string[] | null;
            /** Cert */
            cert?: {
                [key: string]: unknown;
            } | null;
        };
        /** SingleSummarizationResponse */
        SingleSummarizationResponse: {
            /** Summary */
            summary: string;
        };
        /** Software */
        Software: {
            /** Product */
            product?: string | null;
            /** Vendor */
            vendor?: string | null;
            /** Version */
            version?: string | null;
            /** Source */
            source?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Evidence */
            evidence?: components["schemas"]["SoftwareEvidence"][] | null;
            /** Type */
            type?: string[] | null;
            /** Part */
            part?: string | null;
            /** Cpe */
            cpe?: string | null;
            /** Components */
            components?: string[] | null;
        };
        /** SoftwareEvidence */
        SoftwareEvidence: {
            /** Data Path */
            data_path?: string | null;
            /** Found Value */
            found_value?: string | null;
            /** Literal Match */
            literal_match?: string | null;
        };
        /** SummarizationResponse */
        SummarizationResponse: {
            /** Hosts Summary */
            hosts_summary?: string | null;
            /** Web Properties Summary */
            web_properties_summary?: string | null;
            /** Certificates Summary */
            certificates_summary?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** ThreatIntelligence */
        ThreatIntelligence: {
            /** Security Labels */
            security_labels?: string[] | null;
            /** Risk Level */
            risk_level?: string | null;
        };
        /** UsageIndicators */
        UsageIndicators: {
            /** Ever Seen In Scan */
            ever_seen_in_scan?: boolean | null;
        };
        /** Validation */
        Validation: {
            /** Trusted By Major Browsers */
            trusted_by_major_browsers?: boolean | null;
            validation_paths?: components["schemas"]["ValidationPaths"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationPaths */
        ValidationPaths: {
            /** Apple */
            apple?: boolean | null;
            /** Chrome */
            chrome?: boolean | null;
            /** Microsoft */
            microsoft?: boolean | null;
            /** Mozilla */
            mozilla?: boolean | null;
        };
        /** ValidityPeriod */
        ValidityPeriod: {
            /** Not Before */
            not_before?: string | null;
            /** Not After */
            not_after?: string | null;
            /** Length Days */
            length_days?: number | null;
            /** Status */
            status?: string | null;
        };
        /** Vulnerability */
        Vulnerability: {
            /** Cve Id */
            cve_id: string;
            /** Severity */
            severity?: string | null;
            /** Cvss Score */
            cvss_score?: number | null;
            /** Description */
            description?: string | null;
        };
        /** WebEndpoint */
        WebEndpoint: {
            /** Endpoint Type */
            endpoint_type?: string | null;
            /** Path */
            path?: string | null;
            /** Banner */
            banner?: string | null;
            /** Banner Hash Sha256 */
            banner_hash_sha256?: string | null;
            /** Banner Hex */
            banner_hex?: string | null;
            /** Transport Protocol */
            transport_protocol?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** WebPropertiesDataset */
        WebPropertiesDataset: {
            metadata?: components["schemas"]["WebPropertiesDatasetMetadata"];
            /** Web Properties */
            web_properties?: components["schemas"]["WebProperty"][];
        };
        /** WebPropertiesDatasetMetadata */
        WebPropertiesDatasetMetadata: {
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Data Sources */
            data_sources?: string[] | null;
            /** Web Properties Count */
            web_properties_count?: number | null;
            /** Hostnames Analyzed */
            hostnames_analyzed?: string[] | null;
        };
        /** WebProperty */
        WebProperty: {
            /** Port */
            port?: number | null;
            /** Scan Timed */
            scan_timed?: string | null;
            /** Hostname */
            hostname?: string | null;
            /** Labels */
            labels?: string[] | null;
            /** Endpoints */
            endpoints?: components["schemas"]["WebEndpoint"][] | null;
            /** Misconfigs */
            misconfigs?: {
                [key: string]: unknown;
            }[] | null;
            /** Exposures */
            exposures?: {
                [key: string]: unknown;
            }[] | null;
            /** Vulns */
            vulns?: {
                [key: string]: unknown;
            }[] | null;
            /** Software */
            software?: {
                [key: string]: unknown;
            }[] | null;
            /** Hardware */
            hardware?: {
                [key: string]: unknown;
            }[] | null;
            /** Operating System */
            operating_system?: {
                [key: string]: unknown;
            }[] | null;
            /** Tls */
            tls?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** Whois */
        Whois: {
            network?: components["schemas"]["WhoisNetwork"] | null;
        };
        /** WhoisNetwork */
        WhoisNetwork: {
            /** Handle */
            handle?: string | null;
            /** Name */
            name?: string | null;
            /** Cidrs */
            cidrs?: string[] | null;
            /** Updated */
            updated?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    summarize_hosts_summarization_hosts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostsDataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleSummarizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_web_properties_summarization_web_properties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebPropertiesDataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleSummarizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_certificates_summarization_certificates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificatesDataset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleSummarizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_summarization_summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_summarize_summarization_summarize_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
